swagger: "2.0"
info:
  title: Sample API
  description: Sample API Description
  version: 1.0.0

paths:
  /:
    get:
      responses:
        200:
          description: ok

definitions:
  RecordType:
    type: string
    enum:
      - payment
    description: >
      List:
        * payment - payment

  Record:
    type: object
    properties: 
      type:
        $ref: '#/definitions/RecordType'
      id:
        type: string
        format: uuid4
      organisation_id:
        type: string
        format: uuid4
      version:
        type: integer
        minimum: 0
    required:
      - id
      - organisation_id

  AccountAttributes:
    type: object
    properties:
      account_classification:
        type: string
        enum:
          - Personal
          - Business
        description: >
          Classification of account, can be either `Personal` or `Business`. Only used for Confirmation of Payee.
            * `Business` - The account is a business account and the provided information is linked to a business.
            * `Personal` - The account is a personal account and the provided information is linked to an individual.
      bank_id:
        type: string
        maxLength: 11
        description: >
          Local country bank identifier, always a UK sort code for accounts usable with FPS.
      bank_id_code:
        type: string
        enum:
          - GBDSC
        description: >
          Identifies the type of bank ID being used, must be `GBDSC`.
      base_currency:
        type: string
        enum:
          - GBP
        description: >
          ISO 4217 code used to identify the base currency of the account. Always `GBP` for accounts usable with FPS.
      bic:
        type: string
        pattern: '^(.{8}|.{11})$'
        description: >
          SWIFT BIC in either 8 or 11 character format.
      country:
        type: string
        enum:
          - GB
        description: >
          ISO 3166-1 code used to identify the domicile of the account. Always GB for accounts usable with FPS.
      iban:
        type: string
        description: >
          IBAN of the account. Either provided when creating the resource or generated by Form3 for accounts usable with FPS.
      joint_account:
        type: boolean
        description: >
          Flag to indicate if the account is a joint account, set to `true` is this is a joint account. Only used for Confirmation of Payee.
      name_matching_status:
        type: string
        enum:
          - not_supported
          - opted_out
          - supported
          - switched
        description: >
          Describes the status of the account for name matching via Confirmation of Payee. The value determines the code with which Form3 responds to matched Confirmation of Payee requests to this account.
            * `not_supported` - Name matching via Confirmation of Payee is not supported for this account.
            * `opted_out` - This account has been opted out of name matching via Confirmation of Payee.
            * `supported` - Name matching via Confirmation of Payee is supported for this account. This is the default value if the field is not provided during account creation.
            * `switched` - This account has been switched to another organisation using CASS.
      status:
        type: string
        enum:
          - closed
          - confirmed
          - pending
        description: >
          Status of the account. `pending` and `confirmed` are set by Form3, `closed` can be set manually.
            * `closed` - The account has been closed, payments to this account will be rejected with the code defined in `status_reason`.
            * `confirmed` - The account is active and can be used to submit and receive payments.
            * `pending` - The account has been created but not active yet.
      acceptance_qualifier:
        type: string
        enum:
          - after_next_working_day
          - next_calendar_day
          - next_working_day
          - same_day
          - some_other_time
        description: >
          Determines the qualifier code with which payments to the account are accepted. If not present, payments are accepted by default with `0000` (accepted without qualification).
            * `after_next_working_day` - After the next Working Day within the PSD Guidelines, FPS qualifier code `0084`.
            * `next_calendar_day` - On the next calendar day, FPS qualifier code `0082`.
            * `next_working_day` - On the next working day, FPS qualifier code `0083`.
            * `same_day` - On the same day, FPS qualifier code `0081`.
            * `some_other_time` - At an unspecified time and date within the PSD Guidelines, FPS qualifier code `0080`.
      account_number:
        type: string
        minLength: 8
        maxLength: 8
        description: >
          8-digit British domestic account number. Provided when creating the resource or generated by Form3. Not generated if `iban` is provided but this field is empty upon resource creation.
      alternative_names:
        type: array
        maxItems: 3
        items:
          type: string
          maxLength: 140
        description: >
          Alternative primary account names, up to 3 alternative account names with one name in each line of the array. Only used for Confirmation of Payee.
      customer_id:
        type: string
        description: >
          A free-format reference that can be used to link this account to an external system.
      name:
        type: array
        maxItems: 4
        items:
          type: string
          maxLength: 140
        description: >
          Name of the account holder, up to four lines possible.

          For Confirmation of Payee, the following rules apply:
            * Must be the primary account name.
            * For concatenated personal names, joint account names and organisation names, use the first line.
            * If first and last names of a personal name are separated, use the first line for first names, the second line for last names.
            * Titles are ignored and should not be entered.
      reference_mask:
        type: string
        description: >
          Mask to use when validating the `reference` field of inbound payments to the account. Payments without matching reference fields will be rejected.

          Matching rules:
            * `?` matches any character.
            * `#` matches any numeric characters (0-9).
            * `$` matches any alphanumeric character (a-z, A-Z).
            * All other characters are literals. \ can be used to escape control characters to literals.
            * Maximum length 35 characters.
            * `-` and space characters are ignored in the reference when matching.
      secondary_identification:
        type: string
        maxLength: 140
        description: >
          Additional information to identify the account and account holder, can be any type of additional identification, e.g. a building society roll number. Only used for Confirmation of Payee.
      status_reason:
        type: string
        enum:
          - beneficiary_sensitivities
          - business_reasons
          - closed
          - currency
          - deceased
          - stopped
          - terms_and_conditions
          - transferred
        description: >
          Additional account status information when `status` is `closed`, not present when `status` has other values. The FPS code with which inbound payments to the account will be rejected depends on the value of this field.
          * `beneficiary_sensitivities` - Payment cannot be applied because of Beneficiary sensitivities e.g. possible bankruptcy, FPS code 1169. Payment Admission field status_reason will be account_closed_beneficiary_sensitivities.
          * `business_reasons` - For business reasons only, FPS code 1100. Payment Admission field status_reason will be account_closed_business_reasons.
          * `closed` - Beneficiary Account closed, FPS code 1160. Payment Admission field status_reason will be account_closed.
          * `currency` - Account is not in currency quoted, FPS code 1165. Payment Admission field status_reason will be account_closed_currency.
          * `deceased` - Beneficiary deceased, FPS code 1167. Payment Admission field status_reason will be account_closed_beneficiary_deceased.
          * `stopped` - Beneficiary Account stopped, FPS code 1161. Payment Admission field status_reason will be account_closed_stopped.
          * `terms_and_conditions` - Terms and Conditions of Account do not permit crediting of these funds, FPS code 1170. Payment Admission field status_reason will be account_closed_terms_and_conditions.
          * `transferred` - Account transferred, FPS code 1166. Payment Admission field status_reason will be account_closed_transferred.
      switched_account_details:
        type: object
        description: >
          Stores alternate account details to use if the beneficiary account has been switched and payments should be forwarded to the new account.
      user_defined_data:
        type: object
        description: >
          All-purpose list of key-value pairs to store data related to the account. Maximum array length is 5 entries.

          If provided, this array will be copied into each Payment Admission resource relationship where this account is the beneficiary.
      validation_type:
        type: string
        enum:
          - card
          - mandatory_reference
        description: >
          Determines if modcheck validations are carried out on inbound payments to the account.
            * `card` - The account is a collection account for card payments and inbound payments need to have a valid card number in their reference field. Validity is checked by performing a modcheck on the reference field value.
            * `mandatory_reference` - Verify that a reference is provided in the reference field of the Payment resource of the inbound payment.

  Account:
    allOf:
      - $ref: '#/definitions/Record'
      - type: object
        properties:
          attributes:
            allOf:
              - $ref: '#/definitions/AccountAttributes'
              - required:
                  - validation_type
  